model:
  name: "/home/shreya/Nihal/outputs/base_dia_3.5_4B/warmup_merged"


dataset:
  train_path: "/home/shreya/Nihal/data/D30001_warmup_processed.csv"
  text_column: "text"

training:
  do_eval: false
  epochs: 2
  learning_rate: 1e-4
  batch_size: 1
  gradient_accumulation_steps: 8
  logging_steps: 100
  max_seq_length: 1408
  warmup_ratio: 0.03

optimization:
  bf16: true
  gradient_checkpointing: true
  use_gradient_checkpointing: "unsloth"
  packing: false

quantization:
  load_in_4bit: true

lora:
  r: 16
  alpha: 32
  dropout: 0.0

scheduler:
  type: cosine

regularization:
  weight_decay: 0.01

checkpoint:
  save_strategy: steps
  save_steps: 2000
  save_total_limit: 2

  merge_adapter_checkpoint: null
  resume_from_checkpoint: "/home/shreya/Nihal/outputs/D30001_dia_nih/checkpoint-14000"

output:
  output_dir: "/home/shreya/Nihal/outputs/D30001_dia_nih"
